name: Build and Deploy to Minikube
# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Docker image
      run: |
        docker build -t syedmurtaza12/mern-k8s-app:latest .

    - name: Debug Secrets
      run: |
        echo "Checking if secrets are available..."
        if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME is set"
        else
          echo "DOCKER_USERNAME is not set"
        fi
        if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "DOCKER_PASSWORD is set"
        else
          echo "DOCKER_PASSWORD is not set"
        fi

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Attempting to login to Docker Hub..."
        if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
          echo "Error: Docker credentials are not set"
          exit 1
        fi
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push syedmurtaza12/mern-k8s-app:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/mongodb-deployment.yaml
        kubectl apply -f k8s/mongodb-pvc.yaml
        kubectl apply -f k8s/services.yaml 